import type { FinanceData } from '../../types';
import type { PlanningData,MonthProjection } from './types';
import { balanceSummary,displayDate,today } from '../../utils/finance';
import { projection,realized } from './calculations';
import type { Money } from './ui';
export function ProjectionList({months,money}:{months:MonthProjection[];money:Money}) {
 return <div className="projection-list">{months.map(m=><article className="panel" key={m.month}><h3>{m.month.split('-').reverse().join('/')}</h3><dl className="finance-details"><div><dt>Abertura {m===months[0]?'realizada':'prevista'}</dt><dd>{money(m.opening)}</dd></div><div><dt>Entradas previstas</dt><dd>{money(m.income)}</dd></div><div><dt>Recorrentes</dt><dd>{money(m.recurring)}</dd></div><div><dt>Cartões</dt><dd>{money(m.cards)}</dd></div><div><dt>Dívidas</dt><dd>{money(m.debts)}</dd></div><div><dt>Outras despesas previstas</dt><dd>{money(m.other)}</dd></div><div><dt>Transferências (efeito no disponível)</dt><dd>{money(m.transfers)}</dd></div><div><dt>Compromissos totais</dt><dd>{money(m.commitments)}</dd></div><div className="finance-total"><dt>Saldo projetado final</dt><dd>{money(m.closing)}</dd></div></dl></article>)}</div>;
}
export function HomeClarity({data,plan,money,onPlan,onNew}:{data:FinanceData;plan:PlanningData;money:Money;onPlan:()=>void;onNew:()=>void}) {
 const asOf=today(),months=projection(data,plan,asOf),current=months[0],balances=balanceSummary(data.accounts,data.transactions,asOf),actual=realized(data.transactions,plan.card_purchases,asOf.slice(0,7),asOf);
 const totalDebt=plan.debts.reduce((sum,d)=>sum+d.remaining_amount_cents,0);
 return <><section className="balance"><span>Livre no mês</span><h2>{money(current.closing)}</h2><small>PREVISTO · disponível após compromissos até o fim do mês</small><div className="balance-secondary"><div>Saldo disponível <strong>{money(balances.available)}</strong><small>REALIZADO · agora</small></div><div>Compromissos restantes <strong>{money(current.commitments)}</strong></div></div><button onClick={onNew}>+ Nova movimentação</button></section><div className="metrics"><div><small>Receitas previstas restantes</small><strong>{money(current.income)}</strong></div><div><small>Faturas deste mês</small><strong>{money(current.cards)}</strong></div><div><small>Dívidas deste mês</small><strong>{money(current.debts)}</strong></div></div><div className="panel"><dl className="finance-details"><div><dt>Investimentos e reserva</dt><dd>{money(balances.reserve)}</dd></div><div><dt>Patrimônio total</dt><dd>{money(balances.total)}</dd></div><div><dt>Quanto falta pagar em dívidas</dt><dd>{money(totalDebt)}</dd></div><div><dt>Receitas realizadas no mês</dt><dd>{money(actual.income)}</dd></div><div><dt>Despesas realizadas no mês</dt><dd>{money(actual.expense)}</dd></div></dl><small>Patrimônio total: soma das contas, antes de descontar dívidas e cartões. Despesas realizadas incluem compras no cartão, uma vez.</small></div><div className="section-heading"><h2>Próximos compromissos</h2><button onClick={onPlan}>Planejar</button></div>{current.items.filter(c=>c.direction!=='income').length?current.items.filter(c=>c.direction!=='income').slice(0,6).map(c=><div className="account-line" key={c.id}><div><strong>{c.name}</strong><small>{displayDate(c.due)} · {c.due<asOf?'PENDENTE · vencido':'PREVISTO'}</small></div><strong>{money(c.amount)}</strong></div>):<p className="empty">Nenhum compromisso previsto. Adicione recorrentes, cartões ou dívidas em Planejar.</p>}<div className="section-heading"><h2>Projeção · próximos meses</h2><button onClick={onPlan}>Detalhar</button></div><ProjectionList months={months} money={money}/></>;
}
